// Add any additional repositories for your dependencies here

repositories {
    mavenCentral()
    maven {
        name = 'GTNH Maven'
        url = 'https://nexus.gtnewhorizons.com/repository/public/'
    }
    maven {
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    mavenLocal()
}
